In [1]:
print("hello")

hello


In [2]:
import numpy as np

In [4]:
type([1,2,3,4,5])

list

In [5]:
a=np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [6]:
a=np.array(1,2,3,4,5)

TypeError: array() takes from 1 to 2 positional arguments but 5 were given

In [7]:
a.ndim

1

In [9]:
a=np.array([1,2,3,4,5][6,7,8,9,10])

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
/tmp/ipykernel_4111/2319823452.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a=np.array([1,2,3,4,5][6,7,8,9,10])
/tmp/ipykernel_4111/2319823452.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a=np.array([1,2,3,4,5][6,7,8,9,10])
/tmp/ipykernel_4111/2319823452.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a=np.array([1,2,3,4,5][6,7,8,9,10])


TypeError: list indices must be integers or slices, not tuple

In [12]:
a=[[1,2,3],[4,5,6]]
type(a)

list

In [13]:
b=np.array(a)
print(b)

[[1 2 3]
 [4 5 6]]


In [14]:
b.ndim

2

a=[[1,2,3],[4,5,6]]
type(a)

In [16]:
s=[[[1,2,3],[4,5,6],[7,8,9]]]
type(s)

list

In [17]:
c=np.array(s)
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [18]:
c.ndim

3

In [19]:
d=[[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]]
type(d)

list

In [20]:
e=np.array(d)
print(e)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]]]


In [21]:
e.ndim

4

In [22]:
e.shape

(1, 1, 4, 3)

In [23]:
e.dtype

dtype('int64')

In [24]:
e.itemsize

8

In [25]:
e.data

In [26]:
e=np.zeros([2,2])

In [27]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [28]:
np.zeros(e.shape)

array([[0., 0.],
       [0., 0.]])

In [29]:
np.zeros(s.shape)

AttributeError: 'list' object has no attribute 'shape'

In [30]:
np.zeros(c.shape)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])