In [6]:
print("Hello")

Hello


In [12]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([(1,2,3,4),(7,8,9,10)],dtype=int)
print(b)

[[ 1  2  3  4]
 [ 7  8  9 10]]


In [31]:
c=np.zeros((1,1))
print(c)

[[0.]]


In [32]:
c1=np.zeros((2,3))
print(c1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [34]:
c2=np.zeros((3,2,4))
print(c2)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [36]:
c3=np.full((3,4),2)
print(c3)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [37]:
c4=np.random.rand(3,5)
print(c4)

[[0.66683106 0.62759933 0.03001254 0.14729051 0.55663583]
 [0.6168143  0.76633336 0.47247929 0.31527578 0.84172746]
 [0.70279787 0.23352486 0.76359942 0.19401706 0.55588336]]


In [39]:
c5=np.ones((3,4))
print(c5)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [41]:
c6=np.eye(4)
print(c6)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [42]:
d=np.copy(c5)
print(d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [46]:
a.view()


array([1, 2, 3])

In [49]:
b1=a.reshape(3,-1)
b1

array([[1],
       [2],
       [3]])

In [58]:
a

array([1, 2, 3])

In [76]:
z= np.array([5,8,9,1,4])

In [77]:
type(z)

numpy.ndarray

In [80]:
 c=z.sort()
c

In [79]:
print(c)

None


In [89]:
x = np.array([[1,4], [3,1]])
x.sort(axis=0)
x


array([[1, 1],
       [3, 4]])